### ISSUE TITLE
Sign Up Form Validations

### ISSUE THREAD

**Issue by poedude5229** [poedude5229/WuberEats#1]
Sign Up Form Validations: Ran into a strange issue where if I pass the base requirements (all default red messages have dissapeared), there is a remaining validation that becomes active at that point. This is the password confirmation. If for some reason, I my confirmation password does not match and I press the submission button, the form informs me that the passwords do not match, but then, even after correcting the transgression, I cannot get the submit button to become active again...

**Comment by Zachary-Wood** [comment]
Finished up sign up form validations all should work as intended + stress tested
