### ISSUE TITLE
Create README 

### ISSUE THREAD

**Issue by poedude5229** [poedude5229/WuberEats#5]
## What should be in a README?
- Name of the project
- Link to live site
- Optional Link to your backend repo if you have a separate one
- Summary of what the project is and what it does
- Screenshots of your app in action (once completed)
- Instructions on how to build/run the project (installation instructions)
- List of techs/languages/plugins/APIs used
- To-dos/future features
- Technical implementation details
- Anything you had to stop and think about before building
- Descriptions of particular challenges
- Snippets or links to see code for these
- Links to contact you (LinkedIn)
- Endpoints (See example below)*
<img width="983" alt="249298164-c80e52df-478f-4eb5-a034-45393e170078" src="https://github.com/poedude5229/WuberEats/assets/148486236/e021c559-8159-41a2-9e5c-d810468e5363">

## Best Practices
- Divide your README into distinct sections
- List the technologies used at the top of your README for increased visibility
- Include nice screenshots or GIFs to show and demonstrate the features of your application
- Include code snippets
- Include a link to the live site
- Provide instructions for how to install the project (if applicable)
- Include a list of technologies used in the project
- Include a list of any third-party APIs you used in the project

[Example of a README](https://github.com/AppBK/Sweetwafer)
[Markdown Guide Link](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
[Making tables in Markdown Tutorial](https://www.makeuseof.com/tag/learning-markdown-write-web-faster/)

**Comment by verofl** [comment]
Finished and updated the ReadMe
